[package]
name = "h"
version = "0.1.0"
edition = "2018"
description = "Produces the letters in hello world extremely stupidly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
